[#if mode == "create"]
	[@ui.bambooSection dependsOn='projectType' showOn='Maven']
		[#if mavenJob??]
			[@ui.messageBox type="info" titleKey="org.whitesource.bamboo.plugins.projectType.detection.maven" /]
		[#else]
			[@ui.messageBox type="warning" titleKey="org.whitesource.bamboo.plugins.projectType.maven.error" /]
		[/#if]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn='projectType' showOn='Freestyle']
		[@ui.messageBox type="info" titleKey="org.whitesource.bamboo.plugins.projectType.detection.generic" /]
	[/@ui.bambooSection]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.apiKey" name="apiKey" cssClass="long-field" required='true'/]
	[@ww.radio labelKey="org.whitesource.bamboo.plugins.checkPolicies" name="checkPolicies" list="checkPolicyTypes" toggle="true"/]
	<div class="matrix">
	[@ww.radio labelKey="org.whitesource.bamboo.plugins.projectType" name="projectType" list="projectTypes" toggle="true"/]
	</div>
[#elseif mode == "edit"]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.apiKey" name="apiKey" cssClass="long-field" required='true'/]
	[@ww.label labelKey="org.whitesource.bamboo.plugins.projectType" name="projectType"/]
	[@ww.radio labelKey="org.whitesource.bamboo.plugins.checkPolicies" name="checkPolicies" list="checkPolicyTypes" toggle="true"/]
[/#if]
[@ww.textfield labelKey="org.whitesource.bamboo.plugins.wssUrl" name="wss.url" cssClass="long-field" required='false'/]
[@ww.textfield labelKey="org.whitesource.bamboo.plugins.productToken" name="productToken" cssClass="long-field" required='false'/]
[@ww.textfield labelKey="org.whitesource.bamboo.plugins.productVersion" name="productVersion" cssClass="long-field" required='false'/]
[@ww.textfield labelKey="org.whitesource.bamboo.plugins.projectToken" name="projectToken" cssClass="long-field" required='false'/]
[@ui.bambooSection dependsOn='projectType' showOn='Maven']
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.moduleTokens" cssClass="long-field" name="moduleTokens" required='false'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.modulesIncludePattern" name="modulesIncludePattern"  cssClass="long-field" required='false'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.modulesExcludePattern" name="modulesExcludePattern" cssClass="long-field" required='false'/]
	[@ww.checkbox labelKey="org.whitesource.bamboo.plugins.ignorePOM" name="ignorePOM"/]
[/@ui.bambooSection]
[@ui.bambooSection dependsOn='projectType' showOn='Freestyle']
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.filesIncludePattern" name="filesIncludePattern" cssClass="long-field" required='true'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.filesExcludePattern" name="filesExcludePattern" cssClass="long-field" required='false'/]
[/@ui.bambooSection]