[#if mode == "create"]
	[@ui.bambooSection dependsOn='projectType' showOn='Maven']
		[#if mavenJob??]
			[@ui.messageBox type="info" titleKey="org.whitesource.bamboo.plugins.projectType.detection.maven" /]
		[#else]
			[@ui.messageBox type="warning" titleKey="org.whitesource.bamboo.plugins.projectType.maven.error" /]
		[/#if]
	[/@ui.bambooSection]
	[@ui.bambooSection dependsOn='projectType' showOn='Freestyle']
		[@ui.messageBox type="info" titleKey="org.whitesource.bamboo.plugins.projectType.detection.generic" /]
	[/@ui.bambooSection]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.apiKey" name="apiKey" required='true'/]
	[@ww.checkbox labelKey="org.whitesource.bamboo.plugins.checkPolicies" name="checkPolicies"/]
	<div class="matrix">
	[@ww.radio labelKey="org.whitesource.bamboo.plugins.projectType" name="projectType" list="projectTypes" toggle="true"/]
	</div>
[#elseif mode == "edit"]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.apiKey" name="apiKey" required='true'/]
	[@ww.checkbox labelKey="org.whitesource.bamboo.plugins.checkPolicies" name="checkPolicies"/]
	[@ww.label labelKey="org.whitesource.bamboo.plugins.projectType" name="projectType"/]
[/#if]
[@ww.textfield labelKey="org.whitesource.bamboo.plugins.projectToken" name="projectToken" required='false'/]
[@ui.bambooSection dependsOn='projectType' showOn='Maven']
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.moduleTokens" name="moduleTokens" required='false'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.modulesIncludePattern" name="modulesIncludePattern" required='false'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.modulesExcludePattern" name="modulesExcludePattern" required='false'/]
	[@ww.checkbox labelKey="org.whitesource.bamboo.plugins.ignorePOM" name="ignorePOM"/]
[/@ui.bambooSection]
[@ui.bambooSection dependsOn='projectType' showOn='Freestyle']
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.filesIncludePattern" name="filesIncludePattern" required='true'/]
	[@ww.textfield labelKey="org.whitesource.bamboo.plugins.filesExcludePattern" name="filesExcludePattern" required='false'/]
[/@ui.bambooSection]